syntax = "proto3";
package user;
option go_package = "grpcshop/gen/user";

import "google/api/annotations.proto";

service UserService {
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/v1/users"
      body: "*"
    };
  }
  rpc GetUser(GetUserRequest) returns (UserResponse) {
    option (google.api.http) = {
      get: "/v1/users/{user_id}"
    };
  }
}

message RegisterRequest {
  string email = 1;
  string name  = 2;
}
message RegisterResponse { string user_id = 1; }

message GetUserRequest  { string user_id = 1; }
message UserResponse {
  string user_id = 1;
  string email   = 2;
  string name    = 3;
}
